// AUTO-GENERATED BY UpdateMultiplayerVersion.ps1 - DO NOT MODIFY
// (TODO: where is this ^ script? should these UNITY directives be removed?)
#if UNITY_STANDALONE || UNITY_ANDROID || UNITY_GAMECORE || MICROSOFT_GAME_CORE || UNITY_SWITCH || UNITY_PS4 || UNITY_PS5 || MICROSOFT_GDK_SUPPORT
namespace PlayFab.Multiplayer
{
    internal static class Version
    {
        public static readonly string MultiplayerNativeVersion = "Default";
        public static readonly string MultiplayerUnityVersion = "Default";
    }
}
#endif
